In [1]:
from tictactoe_env import TicTacToe
import numpy as np

%load_ext autoreload
%autoreload 2

In [13]:
class RandomPlayer:
    def strategy(self, state):
        possible_steps = state[1]
        return possible_steps[np.random.randint(possible_steps.shape[0])]

In [99]:
class TicTacToeGame:
    def __init__(self, env):
        self.env = env

    def run_episode(self, player_x, player_o):
        state, _, is_done, _ = self.env.reset()
        rewards_x, rewards_o = [], []
        players = [player_x, player_o]
        cur_player = 0
        while not is_done:
            step = players[cur_player].strategy(state)
            state, reward, is_done, _ = self.env.step(step)
            if cur_player == 0:
                rewards_x.append(reward)
            else:
                rewards_o.append(-reward)
            # rewards_x.append(reward)
            # rewards_o.append(-reward)
            cur_player = (cur_player + 1) % 2
        if (len(rewards_x) > len(rewards_o)):
            if (rewards_x[-1] == 1):
                rewards_o.append(-1)
            else:
                rewards_o.append(0)
        
        return rewards_x, rewards_o

In [100]:
env = TicTacToe()

In [101]:
game = TicTacToeGame(env)

In [102]:
game = TicTacToeGame(env)


player_x = RandomPlayer()
player_o = RandomPlayer()

game.run_episode(player_x, player_o)

([0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, -1])

In [66]:
env.reset()

(('111111111',
  array([[0, 0],
         [0, 1],
         [0, 2],
         [1, 0],
         [1, 1],
         [1, 2],
         [2, 0],
         [2, 1],
         [2, 2]], dtype=int64),
  1),
 0,
 False,
 {})

In [16]:
env.printBoard()

-------------
|   |   |   | 
-------------
|   |   |   | 
-------------
|   |   |   | 
-------------


In [17]:
env.step(np.array([0, 0]))

(('211111111',
  array([[0, 1],
         [0, 2],
         [1, 0],
         [1, 1],
         [1, 2],
         [2, 0],
         [2, 1],
         [2, 2]], dtype=int64),
  -1),
 0,
 False,
 {})

In [18]:
env.printBoard()

-------------
| x |   |   | 
-------------
|   |   |   | 
-------------
|   |   |   | 
-------------


In [19]:
env.step(np.array([0, 0]))

(('211111111',
  array([[0, 1],
         [0, 2],
         [1, 0],
         [1, 1],
         [1, 2],
         [2, 0],
         [2, 1],
         [2, 2]], dtype=int64),
  -1),
 -10,
 True,
 {})

In [98]:
env.reset()[0][1][np.random.randint()]

array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [1, 2],
       [2, 0],
       [2, 1],
       [2, 2]], dtype=int64)

In [21]:
env.printBoard()

-------------
|   |   |   | 
-------------
|   |   |   | 
-------------
|   |   |   | 
-------------


In [19]:
env.step([0, 0])

(('211111111',
  array([[0, 1],
         [0, 2],
         [1, 0],
         [1, 1],
         [1, 2],
         [2, 0],
         [2, 1],
         [2, 2]], dtype=int64),
  -1),
 -10,
 True,
 {})

In [ ]:
env

In [6]:
env.step([0, 1])

(('201111111',
  array([[0, 2],
         [1, 0],
         [1, 1],
         [1, 2],
         [2, 0],
         [2, 1],
         [2, 2]], dtype=int64),
  1),
 0,
 False,
 {})

In [7]:
env.printBoard()

-------------
| x | o |   | 
-------------
|   |   |   | 
-------------
|   |   |   | 
-------------
