In [151]:
from tictactoe_env import TicTacToe
import numpy as np

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [152]:
class RandomPlayer:
    def strategy(self, state):
        possible_steps = state[1]
        return possible_steps[np.random.randint(possible_steps.shape[0])]

In [161]:
class TicTacToeGame:
    def __init__(self, env):
        self.env = env

    def run_episode(self, player_x, player_o):
        state, _, is_done, _ = self.env.reset()
        self.env.printBoard()
        rewards_x, rewards_o = [], []
        while not is_done:
            step_x = player_x.strategy(state)
            state, reward_x, is_done, _ = self.env.step(step_x)
            step_o = player_o.strategy(state)
            self.env.printBoard()
            state, reward_o, is_done, _ = self.env.step(step_o)
            rewards_x.append(reward_x)
            rewards_o.append(reward_o)
            self.env.printBoard()
            print(reward_x, reward_o)
        return rewards_x, rewards_o

        

In [162]:
env = TicTacToe()

In [163]:
game = TicTacToeGame(env)

In [165]:
game = TicTacToeGame(env)


player_x = RandomPlayer()
player_o = RandomPlayer()

game.run_episode(player_x, player_o)

-------------
|   |   |   | 
-------------
|   |   |   | 
-------------
|   |   |   | 
-------------
-------------
|   |   |   | 
-------------
|   |   |   | 
-------------
|   |   | x | 
-------------
-------------
|   |   |   | 
-------------
|   | o |   | 
-------------
|   |   | x | 
-------------
0 0
-------------
| x |   |   | 
-------------
|   | o |   | 
-------------
|   |   | x | 
-------------
-------------
| x |   | o | 
-------------
|   | o |   | 
-------------
|   |   | x | 
-------------
0 0
-------------
| x |   | o | 
-------------
|   | o | x | 
-------------
|   |   | x | 
-------------
-------------
| x | o | o | 
-------------
|   | o | x | 
-------------
|   |   | x | 
-------------
0 0
-------------
| x | o | o | 
-------------
|   | o | x | 
-------------
| x |   | x | 
-------------
-------------
| x | o | o | 
-------------
|   | o | x | 
-------------
| x | o | x | 
-------------
0 -1


([0, 0, 0, 0], [0, 0, 0, -1])

In [157]:
env.reset()

(('111111111',
  array([[0, 0],
         [0, 1],
         [0, 2],
         [1, 0],
         [1, 1],
         [1, 2],
         [2, 0],
         [2, 1],
         [2, 2]], dtype=int64),
  1),
 0,
 False,
 {})

In [123]:
env.printBoard()

-------------
|   |   |   | 
-------------
|   |   |   | 
-------------
|   |   |   | 
-------------


-------------
|   |   |   | 
-------------
|   |   | x | 
-------------
|   |   |   | 
-------------


In [98]:
env.reset()[0][1][np.random.randint()]

array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [1, 2],
       [2, 0],
       [2, 1],
       [2, 2]], dtype=int64)

In [21]:
env.printBoard()

-------------
|   |   |   | 
-------------
|   |   |   | 
-------------
|   |   |   | 
-------------


In [19]:
env.step([0, 0])

(('211111111',
  array([[0, 1],
         [0, 2],
         [1, 0],
         [1, 1],
         [1, 2],
         [2, 0],
         [2, 1],
         [2, 2]], dtype=int64),
  -1),
 -10,
 True,
 {})

In [ ]:
env

In [6]:
env.step([0, 1])

(('201111111',
  array([[0, 2],
         [1, 0],
         [1, 1],
         [1, 2],
         [2, 0],
         [2, 1],
         [2, 2]], dtype=int64),
  1),
 0,
 False,
 {})

In [7]:
env.printBoard()

-------------
| x | o |   | 
-------------
|   |   |   | 
-------------
|   |   |   | 
-------------
